package by.epam.javawebtraining.glazunov.webproject.controller;

public enum CommandName {
	SELECT_PAGE,
	CHANGE_LOCALE,
	ADD_CAR,
	SING_IN,
	REGISTRATION,
	GET_ALL_ORDER_BY_ID,
	ADD_ORDER,
	REMOVE_ORDER,
	LOGOUT,
	GET_ALL_ROUTE_BY_ID,
	EDIT_MARK_ROUTE,
	EDIT_CAR_CONDITION,
	CREATE_ROUTE,
	ADD_ROUTE,
	REMOVE_ROUTE,
	GO_TO_SING_IN,
	GO_TO_REGISTRATION,
	GET_ALL_CAR_BY_ID_DRIVER,
	GO_TO_ADD_ORDER,
	GET_ALL_ORDER_WITHOUT_ROUTE,
	GET_ALL_ROUTE,
	GET_ALL_CAR,
	SHOW_EDIT_ORDER_FORM,
	UPDATE_ORDER,
	REMOVE_CAR,
	GET_ALL_DRIVER,
	APPOINT_CAR,
	ADD_CARS_FOR_DRIVER;
	
}
